.TH "COBRA\-ADD" "1" "Dec 2015" "github.com/spf13/cobra" "Cobra Manual"  ""
.nh
.ad l

.SH NAME
.PP
cobra\-add \- Add a command to a Cobra Application


.SH SYNOPSIS
.PP
\fBcobra add\fP [OPTIONS]


.SH DESCRIPTION
.PP
Add (cobra add) will create a new command, with a license and
the appropriate structure for a Cobra\-based CLI application,
and register it to its parent (default RootCmd).

.PP
If you want your command to be public, pass in the command name
with an initial uppercase letter.

.PP
Example: cobra add server  \-> resulting in a new cmd/server.go


.SH OPTIONS
.PP
\fB\-p\fP, \fB\-\-parent\fP="RootCmd"
    name of parent command for this command


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-a\fP, \fB\-\-author\fP="YOUR NAME"
    Author name for copyright attribution

.PP
\fB\-\-config\fP=""
    config file (default is $HOME/.cobra.yaml)

.PP
\fB\-l\fP, \fB\-\-license\fP=""
    Name of license for the project (can provide \fB\fClicensetext\fR in config)

.PP
\fB\-b\fP, \fB\-\-projectbase\fP=""
    base project directory, e.g. github.com/spf13/

.PP
\fB\-\-viper\fP[=true]
    Use Viper for configuration


.SH SEE ALSO
.PP
\fBcobra(1)\fP
